### ISSUE TITLE
Receving meal nutrients

### ISSUE THREAD

**Issue by Dayo-Akinsola** [chingu-voyages/v37-bears-team-09#11]
**__Feature Description__**
Nutrients of uploaded food should be shown to the user when they upload an image to the app.

**__Major User Stories__**
As a user I should be able to ...
- [ ] Create an account.
- [ ] Log in to an account I have created.
- [ ] Take a picture and upload it to the app.
- [ ] Receive the foods and nutrients that are inside the meal I have uploaded.

**__Major Tasks__**

***__Frontend__***
- [ ] Add a button to send a user to the sign up / log in page.
- [ ] Once logged in they should be redirected to some kind of profile page.
- [ ] Image uploading can be handled by allow the user to upload it from a file on their desktop, paste a url or drag & drop.
- [ ] Connect to the backend to receive foods and nutrient information.

***__Backend__***
- [ ] User credentials should be sent to the backend verified and securely stored in a database.
- [ ] Token should be generated to recognise which user is logged in on a device.
- [ ] Images uploaded by a user stored inside a database.
- [ ] Foods and nutrients for a given image should be stored with the image.
- [ ] Backend should connect to the apis to be able to store secrets ( api key etc...) securely.
